# Generated by Django 3.2.18 on 2023-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('thumbnail', models.ImageField(default='', upload_to='images')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
